# New features

In [1]:
from imports import *
%matplotlib inline

In [2]:
df_shapes_log = pd.DataFrame()

## Import datasets processed in previous step

In [3]:
df=pd.read_hdf(config.df_cleaned, 'df')
df_test=pd.read_hdf(config.df_test_cleaned, 'df')

## Add selected new features

In [4]:
def add_new_features(d: pd.DataFrame):
    
    # Add columns that identify perf missing values
    d['perf_6_month_is_na'] = np.where(d.perf_6_month_avg.isna(),1,0)
    d['perf_12_month_is_na'] = np.where(d.perf_12_month_avg.isna(),1,0)
    d['lead_time_is_na'] = np.where(d.lead_time.isna(),1,0)

    # Add column that identify negative inventory values
    d['national_inv_neg'] = np.where(d.national_inv < 0, 1, 0)

    d['forecast_evol_36'] = d.apply(lambda x: fn.variation(x['forecast_3_month']/3, x['forecast_6_month']/6), axis=1)
    d['forecast_evol_39'] = d.apply(lambda x: fn.variation(x['forecast_3_month']/3, x['forecast_9_month']/9), axis=1)
    d['forecast_evol_69'] = d.apply(lambda x: fn.variation(x['forecast_6_month']/6, x['forecast_9_month']/9), axis=1)

    d['sales_evol_13'] = d.apply(lambda x: fn.variation(x['sales_1_month'], x['sales_3_month']/3), axis=1)
    d['sales_evol_16'] = d.apply(lambda x: fn.variation(x['sales_1_month'], x['sales_6_month']/6), axis=1)
    d['sales_evol_19'] = d.apply(lambda x: fn.variation(x['sales_1_month'], x['sales_9_month']/9), axis=1)
    d['sales_evol_36'] = d.apply(lambda x: fn.variation(x['sales_3_month']/3, x['sales_6_month']/6), axis=1)
    d['sales_evol_39'] = d.apply(lambda x: fn.variation(x['sales_3_month']/3, x['sales_9_month']/9), axis=1)
    d['sales_evol_69'] = d.apply(lambda x: fn.variation(x['sales_6_month']/6, x['sales_9_month']/9), axis=1)

In [5]:
add_new_features(df)
add_new_features(df_test)

In [6]:
df

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,national_inv_neg,forecast_evol_36,forecast_evol_39,forecast_evol_69,sales_evol_13,sales_evol_16,sales_evol_19,sales_evol_36,sales_evol_39,sales_evol_69
0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2.0,2.408225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,7.0,2.297397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687855,0.0,1.319508,0.0,10.0,10.0,10.0,0.0,5.0,7.0,7.0,...,0,1.000000,2.000000,0.500000,-1.000000,-1.000000,-1.000000,0.428571,1.142857,0.500000
1687856,-1.0,NaN,0.0,5.0,7.0,9.0,1.0,3.0,3.0,8.0,...,1,0.428571,0.666667,0.166667,0.000000,1.000000,0.125000,1.000000,0.125000,-0.437500
1687857,-1.0,2.408225,0.0,7.0,9.0,11.0,0.0,8.0,11.0,12.0,...,1,0.555556,0.909091,0.227273,-1.000000,-1.000000,-1.000000,0.454545,1.000000,0.375000
1687858,62.0,2.408225,16.0,39.0,87.0,126.0,35.0,63.0,153.0,205.0,...,0,-0.103448,-0.071429,0.035714,0.666667,0.372549,0.536585,-0.176471,-0.078049,0.119512
1687859,19.0,1.741101,0.0,0.0,0.0,0.0,2.0,7.0,12.0,20.0,...,0,0.000000,0.000000,0.000000,-0.142857,0.000000,-0.100000,0.166667,0.050000,-0.100000

In [7]:
df_test

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,national_inv_neg,forecast_evol_36,forecast_evol_39,forecast_evol_69,sales_evol_13,sales_evol_16,sales_evol_19,sales_evol_36,sales_evol_39,sales_evol_69
0,62.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
1,9.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
2,17.0,2.297397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
3,9.0,1.319508,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0,0.0,0.0,0.0,0.0,0.0,-1.0,0.000000,-1.000000,-1.0
4,2.0,2.297397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242070,12.0,2.701920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
242071,13.0,2.701920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
242072,13.0,2.701920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
242073,10.0,2.701920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
242074,2913.0,2.701920,0.0,0.0,0.0,0.0,0.0,30.0,88.0,88.0,...,0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-0.318182,0.022727,0.5

## Export processed data sets to be used in next steps

In [8]:
df.to_hdf(config.df_new_features, 'df', 'w')
df_test.to_hdf(config.df_test_new_features, 'df', 'w')